"""pipeline_segment_model

Revision ID: 01be396511b4
Revises: 215db329c700
Create Date: 2026-03-26 16:51:24.610423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01be396511b4'
down_revision: Union[str, None] = '215db329c700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_nodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('node_type', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.Text(), server_default='operating', nullable=False),
    sa.Column('is_trading_hub', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('hub_code', sa.Text(), nullable=True),
    sa.Column('lng_capacity_bcm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('lng_type', sa.Text(), nullable=True),
    sa.Column('gem_id', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_nodes_geom', 'pipeline_nodes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_pipeline_nodes_id'), 'pipeline_nodes', ['id'], unique=False)
    op.create_table('tariff_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('tariff_type', sa.Text(), nullable=True),
    sa.Column('eur_per_mwh_per_100km', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('fixed_entry_eur_mwh', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_rules_id'), 'tariff_rules', ['id'], unique=False)
    op.create_table('pipeline_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.BigInteger(), nullable=True),
    sa.Column('target', sa.BigInteger(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('pipeline_name', sa.Text(), nullable=True),
    sa.Column('pipeline_code', sa.Text(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('country_codes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('diameter_mm', sa.Integer(), nullable=True),
    sa.Column('pressure_bar', sa.Integer(), nullable=True),
    sa.Column('capacity_mcm_d', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('length_km', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('status', sa.Text(), server_default='operating', nullable=False),
    sa.Column('cost_distance_km', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cost_tariff_eur_mwh', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cost_composite', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('reverse_cost_distance_km', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reverse_cost_tariff_eur_mwh', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('reverse_cost_composite', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tariff_type', sa.Text(), nullable=True),
    sa.Column('tariff_source', sa.Text(), nullable=True),
    sa.Column('tariff_year', sa.Integer(), nullable=True),
    sa.Column('gem_id', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['pipeline_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target'], ['pipeline_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_edges_geom', 'pipeline_edges', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_pipeline_edges_id'), 'pipeline_edges', ['id'], unique=False)
    op.create_table('pipeline_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('IGGIELGN_id', sa.String(), nullable=True),
    sa.Column('from_node_id', sa.String(), nullable=True),
    sa.Column('to_node_id', sa.String(), nullable=True),
    sa.Column('country_code_from', sa.String(length=2), nullable=True),
    sa.Column('country_code_to', sa.String(length=2), nullable=True),
    sa.Column('is_H_gas', sa.Boolean(), nullable=False),
    sa.Column('length_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('diameter_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_cap_M_m3_per_d', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_pressure_bar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['generic_nodes.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['generic_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_segments_geom', 'pipeline_segments', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_pipeline_segments_id'), 'pipeline_segments', ['id'], unique=False)
    op.drop_index('job_inst_un_idx', table_name='batch_job_instance')
    op.drop_table('batch_job_instance')
    op.drop_table('batch_job_execution_context')
    op.drop_index('job_exec_params_fk_idx', table_name='batch_job_execution_params')
    op.drop_table('batch_job_execution_params')
    op.drop_index('job_exec_inst_fk_idx', table_name='batch_job_execution')
    op.drop_table('batch_job_execution')
    op.drop_index('step_exec_job_fk_idx', table_name='batch_step_execution')
    op.drop_table('batch_step_execution')
    op.drop_table('batch_step_execution_context')
    op.drop_index('ix_generic_nodes_id', table_name='generic_nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_generic_nodes_id', 'generic_nodes', ['id'], unique=False)
    op.create_table('batch_step_execution_context',
    sa.Column('step_execution_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('short_context', sa.VARCHAR(length=2500), autoincrement=False, nullable=False),
    sa.Column('serialized_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['step_execution_id'], ['batch_step_execution.step_execution_id'], name='step_exec_ctx_fk'),
    sa.PrimaryKeyConstraint('step_execution_id', name='batch_step_execution_context_pkey')
    )
    op.create_table('batch_step_execution',
    sa.Column('step_execution_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('step_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('job_execution_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('commit_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('read_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('filter_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('write_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('read_skip_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('write_skip_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('process_skip_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rollback_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('exit_code', sa.VARCHAR(length=2500), autoincrement=False, nullable=True),
    sa.Column('exit_message', sa.VARCHAR(length=2500), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_execution_id'], ['batch_job_execution.job_execution_id'], name='job_exec_step_fk'),
    sa.PrimaryKeyConstraint('step_execution_id', name='batch_step_execution_pkey')
    )
    op.create_index('step_exec_job_fk_idx', 'batch_step_execution', ['job_execution_id'], unique=False)
    op.create_table('batch_job_execution',
    sa.Column('job_execution_id', sa.BIGINT(), server_default=sa.text("nextval('batch_job_execution_job_execution_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('job_instance_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('exit_code', sa.VARCHAR(length=2500), autoincrement=False, nullable=True),
    sa.Column('exit_message', sa.VARCHAR(length=2500), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_instance_id'], ['batch_job_instance.job_instance_id'], name='job_inst_exec_fk'),
    sa.PrimaryKeyConstraint('job_execution_id', name='batch_job_execution_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('job_exec_inst_fk_idx', 'batch_job_execution', ['job_instance_id'], unique=False)
    op.create_table('batch_job_execution_params',
    sa.Column('job_execution_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('parameter_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parameter_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parameter_value', sa.VARCHAR(length=2500), autoincrement=False, nullable=True),
    sa.Column('identifying', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_execution_id'], ['batch_job_execution.job_execution_id'], name='job_exec_params_fk')
    )
    op.create_index('job_exec_params_fk_idx', 'batch_job_execution_params', ['job_execution_id'], unique=False)
    op.create_table('batch_job_execution_context',
    sa.Column('job_execution_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('short_context', sa.VARCHAR(length=2500), autoincrement=False, nullable=False),
    sa.Column('serialized_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_execution_id'], ['batch_job_execution.job_execution_id'], name='job_exec_ctx_fk'),
    sa.PrimaryKeyConstraint('job_execution_id', name='batch_job_execution_context_pkey')
    )
    op.create_table('batch_job_instance',
    sa.Column('job_instance_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('job_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('job_key', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('job_instance_id', name='batch_job_instance_pkey'),
    sa.UniqueConstraint('job_name', 'job_key', name='job_inst_un')
    )
    op.create_index('job_inst_un_idx', 'batch_job_instance', ['job_name', 'job_key'], unique=False)
    op.drop_index(op.f('ix_pipeline_segments_id'), table_name='pipeline_segments')
    op.drop_index('idx_pipeline_segments_geom', table_name='pipeline_segments', postgresql_using='gist')
    op.drop_table('pipeline_segments')
    op.drop_index(op.f('ix_pipeline_edges_id'), table_name='pipeline_edges')
    op.drop_index('idx_pipeline_edges_geom', table_name='pipeline_edges', postgresql_using='gist')
    op.drop_table('pipeline_edges')
    op.drop_index(op.f('ix_tariff_rules_id'), table_name='tariff_rules')
    op.drop_table('tariff_rules')
    op.drop_index(op.f('ix_pipeline_nodes_id'), table_name='pipeline_nodes')
    op.drop_index('idx_pipeline_nodes_geom', table_name='pipeline_nodes', postgresql_using='gist')
    op.drop_table('pipeline_nodes')
    # ### end Alembic commands ###
