"""add pipeline infrastructure models

Revision ID: 0490a000984a
Revises: db4bfbcfffd6
Create Date: 2026-03-20 08:29:58.351442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0490a000984a'
down_revision: Union[str, None] = 'db4bfbcfffd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_nodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('node_type', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.Text(), server_default='operating', nullable=False),
    sa.Column('is_trading_hub', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('hub_code', sa.Text(), nullable=True),
    sa.Column('lng_capacity_bcm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('lng_type', sa.Text(), nullable=True),
    sa.Column('gem_id', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nodes_country', 'pipeline_nodes', ['country'], unique=False)
    op.create_index('idx_nodes_geom', 'pipeline_nodes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_nodes_hub', 'pipeline_nodes', ['hub_code'], unique=False, postgresql_where=sa.text('hub_code IS NOT NULL'))
    op.create_index('idx_nodes_type', 'pipeline_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_pipeline_nodes_id'), 'pipeline_nodes', ['id'], unique=False)
    op.create_table('tariff_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('tariff_type', sa.Text(), nullable=True),
    sa.Column('eur_per_mwh_per_100km', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('fixed_entry_eur_mwh', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_rules_id'), 'tariff_rules', ['id'], unique=False)
    op.create_table('pipeline_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.BigInteger(), nullable=True),
    sa.Column('target', sa.BigInteger(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('pipeline_name', sa.Text(), nullable=True),
    sa.Column('pipeline_code', sa.Text(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('country_codes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('diameter_mm', sa.Integer(), nullable=True),
    sa.Column('pressure_bar', sa.Integer(), nullable=True),
    sa.Column('capacity_mcm_d', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('length_km', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('status', sa.Text(), server_default='operating', nullable=False),
    sa.Column('cost_distance_km', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cost_tariff_eur_mwh', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cost_composite', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('reverse_cost_distance_km', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reverse_cost_tariff_eur_mwh', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('reverse_cost_composite', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tariff_type', sa.Text(), nullable=True),
    sa.Column('tariff_source', sa.Text(), nullable=True),
    sa.Column('tariff_year', sa.Integer(), nullable=True),
    sa.Column('gem_id', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['pipeline_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target'], ['pipeline_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edges_geom', 'pipeline_edges', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_edges_name', 'pipeline_edges', ['pipeline_name'], unique=False)
    op.create_index('idx_edges_source', 'pipeline_edges', ['source'], unique=False)
    op.create_index('idx_edges_source_target', 'pipeline_edges', ['source', 'target'], unique=False)
    op.create_index('idx_edges_status', 'pipeline_edges', ['status'], unique=False)
    op.create_index('idx_edges_target', 'pipeline_edges', ['target'], unique=False)
    op.create_index(op.f('ix_pipeline_edges_id'), 'pipeline_edges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_edges_id'), table_name='pipeline_edges')
    op.drop_index('idx_edges_target', table_name='pipeline_edges')
    op.drop_index('idx_edges_status', table_name='pipeline_edges')
    op.drop_index('idx_edges_source_target', table_name='pipeline_edges')
    op.drop_index('idx_edges_source', table_name='pipeline_edges')
    op.drop_index('idx_edges_name', table_name='pipeline_edges')
    op.drop_index('idx_edges_geom', table_name='pipeline_edges', postgresql_using='gist')
    op.drop_table('pipeline_edges')
    op.drop_index(op.f('ix_tariff_rules_id'), table_name='tariff_rules')
    op.drop_table('tariff_rules')
    op.drop_index(op.f('ix_pipeline_nodes_id'), table_name='pipeline_nodes')
    op.drop_index('idx_nodes_type', table_name='pipeline_nodes')
    op.drop_index('idx_nodes_hub', table_name='pipeline_nodes', postgresql_where=sa.text('hub_code IS NOT NULL'))
    op.drop_index('idx_nodes_geom', table_name='pipeline_nodes', postgresql_using='gist')
    op.drop_index('idx_nodes_country', table_name='pipeline_nodes')
    op.drop_table('pipeline_nodes')
    # ### end Alembic commands ###
