"""create shipping lane model

Revision ID: 0dca8017094f
Revises: c0c5d42561ce
Create Date: 2026-05-20 15:51:57.806121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '0dca8017094f'
down_revision: Union[str, None] = 'c0c5d42561ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_lanes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lane_name', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', spatial_index=False, srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shipping_lanes_geom', 'shipping_lanes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_border_nodes_id'), 'border_nodes', ['id'], unique=False)
  
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_border_nodes_id'), table_name='border_nodes')
    op.drop_index('idx_shipping_lanes_geom', table_name='shipping_lanes', postgresql_using='gist')
    op.drop_table('shipping_lanes')
    # ### end Alembic commands ###
