"""add pipeline import chunks table

Revision ID: 220fa51c2809
Revises: bd98d6e10c91
Create Date: 2026-03-24 12:55:46.733789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220fa51c2809'
down_revision: Union[str, None] = 'bd98d6e10c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
