"""add pipeline import chunks table

Revision ID: bd98d6e10c91
Revises: f2b8d3c4e5a6
Create Date: 2026-03-24 12:00:13.233155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd98d6e10c91'
down_revision: Union[str, None] = 'f2b8d3c4e5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_import_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_segment_index', sa.Integer(), nullable=False),
    sa.Column('end_segment_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'success', 'failed')", name='check_chunk_status'),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'chunk_index', name='uq_job_chunk')
    )
    op.drop_index('idx_edges_geom', table_name='pipeline_edges', postgresql_using='gist')
    op.drop_index('idx_edges_name', table_name='pipeline_edges')
    op.drop_index('idx_edges_source', table_name='pipeline_edges')
    op.drop_index('idx_edges_source_target', table_name='pipeline_edges')
    op.drop_index('idx_edges_status', table_name='pipeline_edges')
    op.drop_index('idx_edges_target', table_name='pipeline_edges')
    op.create_index(op.f('ix_pipeline_import_jobs_id'), 'pipeline_import_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_import_segments_gem_id'), 'pipeline_import_segments', ['gem_id'], unique=False)
    op.create_index(op.f('ix_pipeline_import_segments_id'), 'pipeline_import_segments', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_import_segments_job_id'), 'pipeline_import_segments', ['job_id'], unique=False)
    op.drop_index('idx_nodes_country', table_name='pipeline_nodes')
    op.drop_index('idx_nodes_geom', table_name='pipeline_nodes', postgresql_using='gist')
    op.drop_index('idx_nodes_hub', table_name='pipeline_nodes', postgresql_where='(hub_code IS NOT NULL)')
    op.drop_index('idx_nodes_type', table_name='pipeline_nodes')
    op.create_index('idx_pipeline_nodes_geom', 'pipeline_nodes', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pipeline_nodes_geom', table_name='pipeline_nodes', postgresql_using='gist')
    op.create_index('idx_nodes_type', 'pipeline_nodes', ['node_type'], unique=False)
    op.create_index('idx_nodes_hub', 'pipeline_nodes', ['hub_code'], unique=False, postgresql_where='(hub_code IS NOT NULL)')
    op.create_index('idx_nodes_geom', 'pipeline_nodes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_nodes_country', 'pipeline_nodes', ['country'], unique=False)
    op.drop_index(op.f('ix_pipeline_import_segments_job_id'), table_name='pipeline_import_segments')
    op.drop_index(op.f('ix_pipeline_import_segments_id'), table_name='pipeline_import_segments')
    op.drop_index(op.f('ix_pipeline_import_segments_gem_id'), table_name='pipeline_import_segments')
    op.drop_index(op.f('ix_pipeline_import_jobs_id'), table_name='pipeline_import_jobs')
    op.create_index('idx_edges_target', 'pipeline_edges', ['target'], unique=False)
    op.create_index('idx_edges_status', 'pipeline_edges', ['status'], unique=False)
    op.create_index('idx_edges_source_target', 'pipeline_edges', ['source', 'target'], unique=False)
    op.create_index('idx_edges_source', 'pipeline_edges', ['source'], unique=False)
    op.create_index('idx_edges_name', 'pipeline_edges', ['pipeline_name'], unique=False)
    op.create_index('idx_edges_geom', 'pipeline_edges', ['geom'], unique=False, postgresql_using='gist')
    op.drop_table('pipeline_import_chunks')
    # ### end Alembic commands ###
