"""addes maritime_route_vertice

Revision ID: cf7c9652d0b7
Revises: 936d25046abd
Create Date: 2026-06-24 10:14:16.884060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'cf7c9652d0b7'
down_revision: Union[str, None] = '936d25046abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maritime_routes_vertices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('in_edges', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('out_edges', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maritime_routes_vertices_geom', 'maritime_routes_vertices', ['geom'], unique=False, postgresql_using='gist')


    # add source and target columns to maritime_routes table, this will be populated from the maritime_routes_vertices table
    op.add_column('maritime_routes', sa.Column('source', sa.BigInteger(), nullable=True))
    op.add_column('maritime_routes', sa.Column('target', sa.BigInteger(), nullable=True))
   


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('maritime_routes', 'target')
    op.drop_column('maritime_routes', 'source')

    op.drop_index('idx_maritime_routes_vertices_geom', table_name='maritime_routes_vertices', postgresql_using='gist')
    op.drop_table('maritime_routes_vertices')
    # ### end Alembic commands ###
