"""Add role field to user model

Revision ID: f6d51dab5f1d
Revises: cfa2b8819e26
Create Date: 2026-03-18 16:14:18.670601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d51dab5f1d'
down_revision: Union[str, None] = 'cfa2b8819e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    userrole_enum = sa.Enum('CLUSTER_ADMIN', 'COMPANY_OWNER', 'UTILITY_PROVIDER', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    
    # Then add the column with the enum type
    op.add_column('users', sa.Column('role', userrole_enum, nullable=False, server_default='COMPANY_OWNER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column first
    op.drop_column('users', 'role')
    
    # Then drop the enum type
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
