###
GET http://localhost:8000/api/v1/pipelines/route/INET_PL_273_Node_1/INET_PL_273_Node_5

### 14. Get reachable nodes from a specific node (wider budget)
GET http://localhost:8000/api/v1/pipelines/segments

