###
GET http://localhost:8000/api/v1/iggielgn
### 
GET http://localhost:8000/api/v1/iggielgn/segments

### 
GET http://localhost:8000/api/v1/iggielgn/nodes-unified

### 
GET http://localhost:8000/api/v1/iggielgn/nodes
